name: This is unstable build

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build --release
      - name: Create unstable release
        uses: viperproject/create-nightly-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: uuu
          release_name: Unstable release uuu
          body: Body for the release
          keep_num: 0
          keep_tags: false
