on:
  push:
    branches:
      - main

env:
  TAG_NAME: unstable
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: tag-exists-action
        id: check-tag
        uses: mukunku/tag-exists-action@v1.0.0
        with:
          tag: ${{ env.TAG_NAME }}

      - name: Delete previous release
        if: steps.check-tag.outputs.exists == 'true'
        run: |
          git fetch --tags
          gh release delete ${{ env.TAG_NAME }} -y
          git push --delete origin ${{ env.TAG_NAME }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: This is a release
          tag_name: ${{ env.TAG_NAME }}

  linux-build:
    name: Build for linux
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        run: cargo build --release

      - name: Upload binary
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: target/release/learn

  windows-build:
    name: Build for windows
    runs-on: windows-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        run: |
          cargo build --release
          rename .\target\release\learn.exe .\target\release\windows-learn.exe

      - name: Upload binary
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: ./target/release/windows-learn.exe

